import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('trees').del();

  // Inserts seed entries

  await knex('trees').insert([
    {
      id: 'd',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '폴더1',
      tree_type: 'FOLDER',
    },
    {
      id: 'a',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '폴더2',
      tree_type: 'FOLDER',
    },
    {
      id: 'c',
      parent_id: 'a',
      user_id: 'jeonghyeon',
      name: '폴더3',
      tree_type: 'FOLDER',
    },
    {
      id: 'aa',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '폴더4',
      tree_type: 'FOLDER',
    },
    {
      id: 'bb',
      parent_id: 'a',
      user_id: 'jeonghyeon',
      name: '폴더5',
      tree_type: 'FOLDER',
    },
    {
      id: 'cc',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '실행1',
      tree_type: 'EXE',
    },
    {
      id: 'dd',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '실행2',
      tree_type: 'EXE',
    },
    {
      id: 'ee',
      parent_id: 'b',
      user_id: 'jeonghyeon',
      name: '실행3',
      tree_type: 'EXE',
    },
    {
      id: 'ff',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '실행4',
      tree_type: 'EXE',
    },
    {
      id: 'gg',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '실행5',
      tree_type: 'EXE',
    },
    {
      id: 'hh',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '실행6',
      tree_type: 'EXE',
    },
    {
      id: 'ii',
      parent_id: 'd',
      user_id: 'jeonghyeon',
      name: '실행7',
      tree_type: 'EXE',
    },
    {
      id: 'jj',
      parent_id: 'd',
      user_id: 'jeonghyeon',
      name: '사진1',
      tree_type: 'JPG',
    },
    {
      id: 'kk',
      parent_id: 'a',
      user_id: 'jeonghyeon',
      name: '사진2',
      tree_type: 'JPG',
    },
    {
      id: 'll',
      parent_id: 'e',
      user_id: 'jeonghyeon',
      name: '사진3',
      tree_type: 'JPG',
    },
    {
      id: 'mm',
      parent_id: 'f',
      user_id: 'jeonghyeon',
      name: '사진4',
      tree_type: 'JPG',
    },
    {
      id: 'nn',
      parent_id: 'g',
      user_id: 'jeonghyeon',
      name: '사진5',
      tree_type: 'JPG',
    },
    {
      id: 'oo',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '사진6',
      tree_type: 'JPG',
    },
    {
      id: 'pp',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '사진7',
      tree_type: 'JPG',
    },
    {
      id: 'qq',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '사진8',
      tree_type: 'JPG',
    },
    {
      id: 'rr',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '사진9',
      tree_type: 'JPG',
    },
    {
      id: 'ss',
      parent_id: 'f',
      user_id: 'jeonghyeon',
      name: '사진10',
      tree_type: 'JPG',
    },
    {
      id: 'tt',
      parent_id: 'h',
      user_id: 'jeonghyeon',
      name: '사진11',
      tree_type: 'JPG',
    },
    {
      id: 'uu',
      parent_id: 'i',
      user_id: 'jeonghyeon',
      name: '사진12',
      tree_type: 'JPG',
    },
    {
      id: 'vv',
      parent_id: 'j',
      user_id: 'jeonghyeon',
      name: '사진13',
      tree_type: 'JPG',
    },
    {
      id: 'ww',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '사진14',
      tree_type: 'JPG',
    },
    {
      id: 'xx',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악1',
      tree_type: 'MP3',
    },
    {
      id: 'yy',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '음악2',
      tree_type: 'MP3',
    },
    {
      id: 'zz',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악3',
      tree_type: 'MP3',
    },
    {
      id: 'aa',
      parent_id: 'a',
      user_id: 'jeonghyeon',
      name: '음악4',
      tree_type: 'MP3',
    },
    {
      id: 'bbb',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '음악5',
      tree_type: 'MP3',
    },
    {
      id: 'ccc',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '음악6',
      tree_type: 'MP3',
    },
    {
      id: 'ddd',
      parent_id: 'd',
      user_id: 'jeonghyeon',
      name: '음악7',
      tree_type: 'MP3',
    },
    {
      id: 'eee',
      parent_id: 'd',
      user_id: 'jeonghyeon',
      name: '음악8',
      tree_type: 'MP3',
    },
    {
      id: 'fff',
      parent_id: 'root',
      user_id: 'jeonghyeon',
      name: '음악9',
      tree_type: 'MP3',
    },
    {
      id: 'ggg',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악10',
      tree_type: 'MP3',
    },
    {
      id: 'hhh',
      parent_id: 'root',
      user_id: 'jeonghyeon',
      name: '음악11',
      tree_type: 'MP3',
    },
    {
      id: 'iii',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악12',
      tree_type: 'MP3',
    },
    {
      id: 'jjj',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악13',
      tree_type: 'MP3',
    },
    {
      id: 'kkk',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악14',
      tree_type: 'MP3',
    },
    {
      id: 'lll',
      parent_id: 'c',
      user_id: 'jeonghyeon',
      name: '음악15',
      tree_type: 'MP3',
    },
    {
      id: 'mmm',
      parent_id: '',
      user_id: 'jeonghyeon',
      name: '음악16',
      tree_type: 'MP3',
    },
    {
      id: 'nnn',
      parent_id: 'root',
      user_id: 'jeonghyeon',
      name: '음악17',
      tree_type: 'MP3',
    },
  ]);
}
